# Generated by Django 4.0.4 on 2023-02-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_listing', '0001_initial'),
    ]

    operations = [
    ]
