# Generated by Django 4.0.4 on 2023-02-26 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products_listing.product'),
            preserve_default=False,
        ),
    ]
