# Generated by Django 4.0.4 on 2023-02-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_listing', '0004_alter_productvariation_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_listing.product'),
        ),
    ]
